#!/bin/bash

# This script returns the numerically greatest command 
# line argument. It splits the argument list into one
# value per line, sort numerically, and selects the last.

printf "%d\n" ${*} | sort -n | tail -n 1
