#!/bin/sh

# This script prints the number of subdirectories that 
# are directly contained within a directory specified 
# by the first parameter. Do not include subdirectories 
# of subdirectories, etc., or directories whose name 
# begins with "." (e.g. '.' or '..') in the count.
 
cd "${1}"
find . -maxdepth 1 -type d -not -name '.*' | wc -l
