#!/bin/bash
# Name: problem4
# This script will take zero or more numeric parameters and prints the sum of # the their values
# For example: bash problem4 1 2 3 4 5 then prints '15'

n=$( echo "${*}" | tr " " +)
echo $(( "$n" ))
